openapi: 3.0.1
info:
    title: dalle Plugin
    description: Plugin to imagine images from dalle.
    version: "v1"
servers:
    - url: https://dalle-tests.vercel.app/
paths:
    api/hello:
        post:
            operationId: imagine 
            summary: Retrieve an image
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/addPrompt"
            responses:
                "200":
                    description: OK

components:
    schemas:
        addPrompt:
            type: object
            required:
                - prompt
            properties:
                prompt:
                    type: string
                    description: the prompt used by Dalle.
                    required: true
