import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useState} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [img, setImg]  = useState('');
  const [prompt, setPrompt] = useState('');

  const fetchImages = async (prompt: string) => {
    const img = fetch('api/hello', {
      method: 'POST',
      body: JSON.stringify(prompt)
    })
    return img;
  }
    const showImages = () => {
      fetchImages(prompt)
      .then(response => response.json())
      .then(data => setImg(data.img))
    }
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input onChange={ (e) => setPrompt(e.target.value)}/>
        <button onClick={showImages}> Mostrar imagenes! </button>
        {
        img && 
          <Image src={img} alt="auto generated image" width={1024} height={1024}/>
        }
      </main>
    </>
  )
}
